---
title: "News"
output:
  distill::distill_article:
    toc: false
---

```{css, echo = FALSE}
d-article h2 {
  font-family: Rubik;
  font-size: 3em;
  text-align: center;
  border-bottom: 3px solid black;
}

d-article h3 {
  font-size: 1.5em;
  text-align: center;
  font-variant: small-caps;
  font-family: Bitter;
  letter-spacing: .2em;
}

li::marker {
  font-size: 1.2em;
}
```

For more of my personal news external/tangential to [research](https://yjunechoe.github.io/research.html)

## 2023

### August

- I was unfortunately not able to make it in person to [JSM 2023](https://ww2.aievolution.com/JSMAnnual/index.cfm?do=ev.viewEv&ev=2860) but have my [pre-recorded talk](https://youtu.be/613Q0j6Kjm0?feature=shared) has been uploaded!

### June

- My package [jlmerclusterperm](https://yjunechoe.github.io/jlmerclusterperm/) was published on CRAN!

### April

- I was accepted to [SMLP](https://vasishth.github.io/smlp2023/) (Summer School on Statistical Methods for Linguistics and Psychology), to be held in September at the University of Potsdam, Germany! I will be joining the "Advanced methods in frequentist statistics with Julia" stream. Huge thanks to [MindCORE](https://mindcore.sas.upenn.edu/) for funding my travels to attend!

### January

- I received the ASA Statistical Computing and Graphics student [award](https://community.amstat.org/jointscsg-section/awards/student-paper-competition) for my paper [Sublayer modularity in the Grammar of Graphics](static/papers/Choe_2022_SublayerGG.pdf)! I will be presenting my work at the 2023 Joint Statistical Meetings in Toronto in August.

## 2022

### September

- I was invited to a Korean data science **podcast** [dataholic (데이터홀릭)](https://www.youtube.com/c/dataholic4) to talk about my experience presenting at the RStudio and useR conferences! [Part 1](https://www.youtube.com/watch?v=Avagxy2PNhg), [Part 2](https://www.youtube.com/watch?v=S4APUKuDUtM)

### August

- I led a [**workshop** on IBEX and PCIbex](https://github.com/yjunechoe/IBEX-Workshop-Materials/blob/master/2022-ibex-pcibex-workshop-slides.pdf) with [Nayoun Kim](https://nayounkimlinguist.com/) at the [Seoul International Conference on Linguistics (SICOL 2022)](https://sicol2022.creatorlink.net/). 

### July

- I attended my first in-person R conference at [rstudio::conf(2022)](https://rstudioconf2022.sched.com/?iframe=no) and gave a [**talk** on ggplot internals](https://www.youtube.com/watch?v=dUBnitXf5mk&list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH&index=38).

### June

- I gave a [**talk**](https://www.youtube.com/watch?v=2JX8zu4QxMg&t=2959s) on my package [`{ggtrace}`](https://yjunechoe.github.io/ggtrace/) at the [useR! 2022 conference](https://user2022.r-project.org/). I was awarded the diversity scholarship which covered my registration and workshop fees. [My reflections](https://yjunechoe.github.io/posts/2022-07-30-user2022/)

- I gave a [**talk**](https://www.youtube.com/watch?v=c5ydz-Ha61I&t=1190s) at [RLadies philly](https://www.rladiesphilly.org/) on using dplyr's slice() function for row-relational operations.

## 2021

### July

- My [**tutorial** on custom fonts in R](https://yjunechoe.github.io/posts/2021-06-24-setting-up-and-debugging-custom-fonts/) was **featured as a highlight** on the [R Weekly podcast](https://share.fireside.fm/episode/87RSVeFz+alD0Og1X?t=247)!

### June

- I gave a [**talk**](https://www.youtube.com/embed/guzjt7xh2Cw?start=3787) at [RLadies philly](https://www.rladiesphilly.org/) on using icon fonts for data viz! I also wrote a follow-up [blog post](https://yjunechoe.github.io/posts/2021-06-24-setting-up-and-debugging-custom-fonts/) that goes deeper into font rendering in R.

### May

- [SnowGlobe](https://snowglobe.soc.northwestern.edu/), a project started in my undergrad, was featured in an [article](https://sites.northwestern.edu/northwesternlibrary/2021/05/11/student-developed-app-expedites-time-consuming-research-task/) by the Northwestern University Library. We also had a [**workshop** for SnowGlobe](https://www.eventbrite.com/e/an-introduction-to-snowglobe-a-tool-for-systematic-reviews-tickets-149045397797#) which drew participants from over a hundred universities!

### January

- I joined [Nayoun Kim](https://nayounkimlinguist.com/) for a [**workshop** on experimental syntax](https://github.com/yjunechoe/IBEX-Workshop-Materials/blob/master/2021-ibex-workshop-slides.pdf) conducted in Korean and held at Sungkyunkwan University (Korea). I helped design [materials](https://github.com/yjunechoe/IBEX-Workshop-Materials) for a session on **scripting online experiments with IBEX**, including [interactive slides](https://ibex-workshop-slides.netlify.app/) made with R!


## 2020

### November

- I joined designer [Will Chase](https://www.williamrchase.com/) on his [**stream**](https://www.youtube.com/watch?v=Z0NVmQXYjac) to talk about the psycholinguistics of speech production for a data viz project on Michael's speech errors in The Office. It was a very cool and unique opportunity to bring my two interests together!

### October

- My [**tutorial** on {ggplot2} stat_*() functions](https://yjunechoe.github.io/posts/2020-09-26-demystifying-stat-layers-ggplot2/) was **featured as a highlight** on the [R Weekly podcast](https://rweekly.fireside.fm/8?t=251), which curates weekly updates from the R community.

- I became a **data science tutor** at [MindCORE](https://mindcore.sas.upenn.edu/) to help researchers at Penn with data visualization and R programming.

### September

- I have moved to Philadelphia to **start my PhD in Linguistics at the University of Pennsylvania**!

### June

- **I graduated from Northwestern University** with a B.A. in Linguistics (with honors)! I was also elected into Phi Beta Kappa and appointed as the Senior Marshal for Linguistics.