---
title: "Resources"
description: |
  Mostly for R and data visualization
output:
  distill::distill_article:
    toc: true
---

## Linguistics

- Scripting online experiments with IBEX (workshop [slides](https://ibex-workshop-slides.netlify.app/) & [materials](https://github.com/yjunechoe/IBEX-Workshop-Materials) with Nayoun Kim)


## Data Visualization

- {ggplot2} style guide and showcase - [most recent version (2/10/2021)](https://yjunechoe.netlify.app/flipbooks/ggplot2_master/feb_2020_ggplot2.html)

- Cracking open the internals of ggplot: A {ggtrace} showcase - [slides](https://yjunechoe.github.io/ggtrace-talk)


## Packages and software

- [{ggtrace}](https://yjunechoe.github.io/ggtrace/index.html): R package for exploring, debugging, and manipulating ggplot internals by exposing the underlying object-oriented system in functional programming terms.

- [{penngradlings}](https://github.com/yjunechoe/penngradlings): R package for the University of Pennsylvania Graduate Linguistics Society.

- [{LingWER}](https://github.com/yjunechoe/LingWER): R package for linguistic analysis of Word Error Rate for evaluating transcriptions and other speech-to-text output, using a deterministic matrix-based search algorithm optimized for R.

- [{gridAnnotate}](https://github.com/yjunechoe/gridAnnotate): R package for interactively annotating figures from the plot pane, using {grid} graphical objects.

- [SnowGlobe](https://snowglobe.soc.northwestern.edu/): A tool for meta-analysis research. Developed with Jinnie Choi, Sean McWeeny, and Elizabeth Norton, with funding from the Northwestern University Library. Currently under development but basic features are functional. Validation experiments and guides at [OSF repo](https://osf.io/u25rn/).


## Tutorial Blog Posts

- {ggplot2} stat_*() functions [[post](https://yjunechoe.github.io/posts/2020-09-26-demystifying-stat-layers-ggplot2/)]

- Custom fonts in R [[post](https://yjunechoe.github.io/posts/2021-06-24-setting-up-and-debugging-custom-fonts/)]

- {purrr} reduce() family [[post1](https://yjunechoe.github.io/posts/2020-12-13-collapse-repetitive-piping-with-reduce/), [post2](https://yjunechoe.github.io/posts/2021-01-17-random-sampling-a-table-animation/)]

- The correlation parameter in {lme4} mixed effects models [[post](https://yjunechoe.github.io/posts/2020-06-07-correlation-parameter-mem/)]

- Shortcuts for common chain of {dplyr} functions [[post](https://yjunechoe.github.io/posts/2020-08-07-saving-a-line-of-piping/)]

- Plotting highly-customizable treemaps with {treemap} and {ggplot2} [[post](https://yjunechoe.github.io/posts/2020-06-30-treemap-with-ggplot/)]


## By others

**Tutorials**:

- [A ggplot2 Tutorial for Beautiful Plotting in R](https://cedricscherer.netlify.app/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/) by Cédric Scherer

- [ggplot2 Wizardry Hands-On](https://z3tt.github.io/OutlierConf2021/) by Cédric Scherer

- [ggplot2 workshop](https://www.youtube.com/watch?v=h29g21z0a68) by Thomas Lin Pedersen

**Books**:

- [R for Data Science](https://r4ds.had.co.nz/) by Hadley Wickham and Garrett Grolemund

- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) by Yihui Xie, J. J. Allaire, and Garrett Grolemund

- [ggplot2: elegant graphics for data analysis](https://ggplot2-book.org/) by Hadley Wickham, Danielle Navarro, and Thomas Lin Pedersen

- [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) by Claus O. Wilke

- [Efficient R Programming](https://csgillespie.github.io/efficientR/) by Colin Gillespie and Robin Lovelace

- [Advanced R](https://adv-r.hadley.nz/) by Hadley Wickham
