---
title: "A pretty decent usecase for override.aes"
description: |
  A short post on linetype legends
categories:
  - data visualization
  - ggplot2
base_url: https://yjunechoe.github.io
author:
  - name: June Choe
    affiliation: University of Pennsylvania Linguistics
    affiliation_url: https://live-sas-www-ling.pantheon.sas.upenn.edu/
    orcid_id: 0000-0002-0701-921X
date: "2024-10-18"
output:
  distill::distill_article:
    include-after-body: "highlighting.html"
    toc: true
    self_contained: false
    css: "../../styles.css"
editor_options: 
  chunk_output_type: console
preview: preview.png
draft: true
---

Earlier today I saw a line plot that was borderline a chart crime. It visualized irritating political content that I don't want to spread, so instead of showing that plot I've replicated the look of it below:

```{r}
set.seed(123)
library(tidyverse)
df <- expand_grid(cat = c("Persian", "Sphynx"), food = c("fish", "chicken")) %>% 
  mutate(
    ymean = c(2,4,8,10)
  ) %>% 
  group_by(cat, food) %>% 
  reframe(
    x = 1:10,
    y = rnorm(10, ymean) * x/10 * 2
  )

p_base0 <- df %>% 
  ggplot(aes(x, y, color = cat)) +
  labs(
    y = "Food preference score",
    x = "Days on diet"
  )
p_base <- p_base0 +
  geom_line(
    aes(linetype = food, alpha = food),
    linewidth = 1.5
  ) +
  scale_alpha_manual(values = c(.5, 1))

p_bad <- p_base +
  scale_linetype_manual(values = c(1, 5)) +
  ggtitle("Bad plot")
p_bad
```



```{r}
p_corrected_1 <- p_base +
  scale_linetype_manual(values = c(1, 3)) +
  ggtitle("Fix via different linetype")
p_corrected_1
```

```{r}
p_corrected_2 <- p_bad +
  theme(
    legend.position = "top",
    legend.key.width = unit(.1, "npc")
  ) +
  ggtitle("Fix via stretching out legend keys")
p_corrected_2
```

```{r}
p_corrected_3 <- p_base +
  scale_linetype_manual(
    values = c(1, 5),
    guide = guide_legend(override.aes = list(linetype = c("solid", "11")))
  ) +
  ggtitle("Fix via override.aes")
p_corrected_3
```


## Direct labelling

```{r}
library(geomtextpath)
p_base0 +
  geom_textpath(
    aes(color = cat, label = cat),
    size = 20,
    linetype = NA, # text_only = TRUE
    alpha = .5,
    spacing = 100,
    text_smoothing = 50,
    data = . %>%
      summarize(y = mean(y), .by = c(cat, x))
  ) +
  geom_textpath(
    aes(color = cat, label = food, group = interaction(cat, food))
  ) +
  guides(color = guide_none()) +
  scale_discrete_manual(
    aesthetics = "label",
    values = c("chicken" = ".", "fish" = "..")
  )
```

