# /// script
# requires-python = ">=3.10"
# dependencies = ["beautifulsoup4==4.13.4"]
# ///
"""Grandfather distill-era posts into the Quarto site.

Runs as the Quarto `pre-render` hook (see _quarto.yml). For every post in the
snapshot at _distill/posts/<slug>/ (the rendered distill output), it writes
posts/<slug>/index.qmd containing the distill article as raw HTML, plus the
post's assets. Headings become markdown headings so Quarto builds the TOC and
anchors. Widget libraries are copied to distill_libs/.

Rules:
  - Generated folders hold a `.gitignore` containing `*` (the marker). Git
    ignores them, and this script owns them: they are rebuilt every render.
  - A posts/<slug>/ folder without the marker is a live post (rendered from
    its own index.qmd). It is never touched. Use _tools/promote.py to make one.
  - Output is deterministic and files are only rewritten when their content
    changes, so repeated renders are idempotent. Each index.qmd's mtime is
    pinned to the post date, so a fresh checkout renders the same bytes.

Treat this file and the snapshot as frozen. Changing either changes how every
legacy post looks.
"""

import json
import os
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

from bs4 import BeautifulSoup, Comment, NavigableString, Tag

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "_distill" / "posts"
SNAPSHOT_LIBS = ROOT / "_distill" / "site_libs"
POSTS = ROOT / "posts"
LIBS = ROOT / "distill_libs"
MARKER = ".gitignore"
MARKER_TEXT = "# Generated by _distill/wrap.py on every render. Do not edit.\n*\n"

# Head dependencies that belong to distill or the distill site chrome.
DISTILL_DEP = re.compile(
    r"(font-awesome|headroom|autocomplete|fuse|header-attrs|popper|tippy|anchor-"
    r"|bowser|webcomponents|distill-|styles\.css)"
)

MATHJAX = '<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" async></script>'

LAYOUT_TO_COLUMN = {
    "l-body-outset": "body-outset",
    "l-page": "page",
    "l-page-outset": "page",
    "l-screen": "screen",
    "l-screen-inset": "screen-inset",
}


# ---------------------------------------------------------------- helpers


def parse_date(x):
    """Distill dates look like 06-07-2020, 1-16-2020, or 2023-12-31."""
    x = str(x).strip().strip('"')
    for fmt in ("%m-%d-%Y", "%Y-%m-%d"):
        try:
            return datetime.strptime(x, fmt).date().isoformat()
        except ValueError:
            pass
    return None


def folder_date(slug):
    m = re.match(r"(\d{4})-(\d{2})-(\d{2})", slug)
    return "-".join(m.groups()) if m else None


def yaml_str(s):
    return json.dumps(str(s), ensure_ascii=False)


def front_matter(fm):
    """Small, deterministic YAML writer for the keys used here."""
    lines = ["---"]
    for k, v in fm.items():
        if k == "author":
            lines.append("author:")
            for a in v:
                lines.append(f"  - name: {yaml_str(a['name'])}")
                if a.get("orcid"):
                    lines.append(f"    orcid: {yaml_str(a['orcid'])}")
                if a.get("affiliation"):
                    lines.append("    affiliations:")
                    lines.append(f"      - name: {yaml_str(a['affiliation'])}")
                    if a.get("affiliation_url"):
                        lines.append(f"        url: {yaml_str(a['affiliation_url'])}")
        elif isinstance(v, list):
            lines.append(f"{k}:")
            lines.extend(f"  - {yaml_str(x)}" for x in v)
        else:
            lines.append(f"{k}: {yaml_str(v)}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def from_r_json(x):
    """Decode the jsonlite-serialized R list distill embeds in each page."""
    if not isinstance(x, dict) or "type" not in x:
        return x
    vals = [from_r_json(v) for v in x.get("value", [])]
    names = x.get("attributes", {}).get("names", {}).get("value")
    if names:
        return dict(zip(names, vals))
    if x["type"] != "list" and len(vals) == 1:
        return vals[0]
    return vals


def as_list(x):
    return x if isinstance(x, list) else [x]


def raw_html(text):
    """A pandoc raw HTML block, fenced longer than any backtick run inside."""
    text = text.strip("\n")
    if not text.strip():
        return ""
    runs = [len(m) for m in re.findall(r"^\s*(`{3,})", text, re.M)]
    f = "`" * max([3] + [n + 1 for n in runs])
    return f"{f}{{=html}}\n{text}\n{f}\n"


def heading_md(tag):
    """Inline markdown for the contents of a heading tag."""

    def esc(s):
        return re.sub(r"([\\`*_\[\]<>#])", r"\\\1", s)

    def walk(node):
        if isinstance(node, Comment):
            return ""
        if isinstance(node, NavigableString):
            return esc(str(node))
        inner = "".join(walk(c) for c in node.children)
        if node.name == "code":
            t = node.get_text()
            f = "``" if "`" in t else "`"
            return f"{f}{t}{f}"
        if node.name in ("em", "i"):
            return f"*{inner}*"
        if node.name in ("strong", "b"):
            return f"**{inner}**"
        if node.name == "a" and node.get("href"):
            return f"[{inner}]({node['href']})"
        return inner

    return " ".join(walk(tag).split())


# ---------------------------------------------------------------- sync


def sync_dir(dst, files, marker=True):
    """Make dst hold exactly `files` ({relpath: bytes | Path}) plus the marker,
    rewriting only files whose content changed."""
    if marker:
        files = {**files, MARKER: MARKER_TEXT.encode()}
    dst.mkdir(parents=True, exist_ok=True)
    for rel, src in files.items():
        out = dst / rel
        data = src.read_bytes() if isinstance(src, Path) else src
        if out.is_file() and out.stat().st_size == len(data) and out.read_bytes() == data:
            continue
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(data)
    keep = {Path(r).as_posix() for r in files}
    for p in sorted(dst.rglob("*"), reverse=True):
        rel = p.relative_to(dst).as_posix()
        if p.is_file() and rel not in keep:
            p.unlink()
        elif p.is_dir() and not any(p.iterdir()):
            p.rmdir()


def tree(src, skip=()):
    return {
        p.relative_to(src).as_posix(): p
        for p in sorted(src.rglob("*"))
        if p.is_file() and p.relative_to(src).as_posix() not in skip
    }


def is_generated(d):
    m = d / MARKER
    return m.is_file() and m.read_text(encoding="utf8").startswith(MARKER_TEXT.splitlines()[0])


# ---------------------------------------------------------------- wrap


def wrap(slug, libs_needed):
    """Return ({relpath: bytes | Path}) for posts/<slug>/."""
    src = SNAPSHOT / slug
    soup = BeautifulSoup((src / "index.html").read_text(encoding="utf8"), "html.parser")

    meta = from_r_json(json.loads(soup.find("script", id="radix-rmarkdown-metadata").string))
    fm = {"title": meta["title"]}
    if meta.get("description"):
        fm["description"] = str(meta["description"]).strip()
    if meta.get("author"):
        fm["author"] = [
            {"name": a["name"], "orcid": a.get("orcid_id"), "affiliation": a.get("affiliation"),
             "affiliation_url": a.get("affiliation_url")} if isinstance(a, dict) else {"name": a}
            for a in as_list(meta["author"])
        ]
    fm["date"] = parse_date(meta.get("date")) or folder_date(slug)
    if meta.get("categories"):
        fm["categories"] = as_list(meta["categories"])
    if meta.get("preview"):
        fm["image"] = meta["preview"]

    article = soup.select_one("div.d-article")
    for sel in ("div.d-contents", "div.article-footer", "pre.distill-force-highlighting-css"):
        for t in article.select(sel):
            (t.parent if t.name == "pre" else t).decompose()
    for c in article.find_all(string=lambda s: isinstance(s, Comment)):
        c.extract()
    for t in article.select("div.layout-chunk"):
        if not t.get_text(strip=True) and not t.find(True):
            t.decompose()

    # Head dependencies (htmlwidgets, panelset, pagedtable, ...)
    deps = []
    for t in soup.head.find_all(["script", "link"]):
        ref = t.get("src") or t.get("href")
        if not ref or ref.startswith("http") or DISTILL_DEP.search(ref):
            continue
        if t.name == "link" and "stylesheet" not in (t.get("rel") or []):
            continue
        m = re.match(r"^(?:\.\./)+site_libs/([^/]+)/", ref)
        if m:
            libs_needed.add(m.group(1))
            ref = ref.replace(m.group(0), f"../../distill_libs/{m.group(1)}/")
            t["src" if t.name == "script" else "href"] = ref
        if "jquery" in ref and any("jquery" in d for d in deps):
            continue
        deps.append(str(t))
    # jQuery is only worth loading if something else might use it
    body_scripts = [s for s in article.find_all("script") if s.get("type") != "application/json"]
    if all("jquery" in d for d in deps) and not body_scripts:
        deps = []
    # Math lives in raw HTML, which Quarto does not scan, so load MathJax here
    if article.select_one("span.math"):
        deps.append(MATHJAX)

    # Keep distill-era tables exactly as rendered (no Quarto table restyling)
    fm["html-table-processing"] = "none"
    # Publish every file the distill site published for this post, referenced
    # or not, so existing URLs (hotlinked figures, social cards) keep working
    fm["resources"] = ["**", "!index.qmd", "!distill-deps.html"]

    out = tree(src, skip={"index.html"})
    if deps:
        out["distill-deps.html"] = ("\n".join(deps) + "\n").encode()
        fm["include-in-header"] = "distill-deps.html"

    # Walk the top level of the article
    parts, buf = [], []

    def flush():
        if buf:
            parts.append(raw_html("".join(buf)))
            buf.clear()

    for node in list(article.children):
        if isinstance(node, Tag) and re.fullmatch(r"h[1-6]", node.name):
            flush()
            anchor = f" {{#{node['id']}}}" if node.get("id") else ""
            parts.append("#" * int(node.name[1]) + " " + heading_md(node) + anchor + "\n")
        elif isinstance(node, Tag) and node.name == "aside":
            flush()
            parts.append("::: {.column-margin}\n" + raw_html(node.decode_contents()) + ":::\n")
        elif isinstance(node, Tag) and node.get("data-layout") in LAYOUT_TO_COLUMN:
            flush()
            col = LAYOUT_TO_COLUMN[node["data-layout"]]
            parts.append(f"::: {{.column-{col}}}\n" + raw_html(str(node)) + ":::\n")
        else:
            buf.append(str(node))
    flush()

    # Nested asides (inside panelsets etc.) still get margin styling
    body = "\n".join(p for p in parts if p)
    body = body.replace("<aside>", '<div class="column-margin">').replace("</aside>", "</div>")

    note = (
        f"<!-- Generated by _distill/wrap.py from _distill/posts/{slug}/index.html.\n"
        f"     Do not edit. To render this post from source, run _tools/promote.py {slug}. -->\n\n"
    )
    out["index.qmd"] = (front_matter(fm) + "\n" + note + body).encode("utf8")
    return out


def stamp(qmd):
    """Quarto uses the input file's mtime for sitemap <lastmod> and listing
    sort keys. Pin it to the post date so output does not depend on when the
    repo was checked out."""
    m = re.search(r'^date: "(\d{4}-\d{2}-\d{2})"$', qmd.read_text(encoding="utf8"), re.M)
    t = datetime.strptime(m.group(1), "%Y-%m-%d").replace(tzinfo=timezone.utc).timestamp()
    os.utime(qmd, (t, t))


def main():
    libs_needed = set()
    wrapped, live = [], []
    for src in sorted(p for p in SNAPSHOT.iterdir() if p.is_dir()):
        dst = POSTS / src.name
        if dst.exists() and not is_generated(dst):
            live.append(src.name)
            continue
        sync_dir(dst, wrap(src.name, libs_needed))
        stamp(dst / "index.qmd")
        wrapped.append(src.name)

    # Generated folders whose snapshot is gone
    for d in sorted(POSTS.iterdir()) if POSTS.exists() else []:
        if d.is_dir() and is_generated(d) and not (SNAPSHOT / d.name).is_dir():
            shutil.rmtree(d)

    libs = {}
    for lib in sorted(libs_needed):
        libs.update({f"{lib}/{k}": v for k, v in tree(SNAPSHOT_LIBS / lib).items()})
    # No marker here: Quarto copies distill_libs/ into docs/ as a resource, and
    # a copied `.gitignore` with `*` would keep docs/distill_libs/ out of git.
    # The root .gitignore ignores distill_libs/ instead.
    sync_dir(LIBS, libs, marker=False)

    print(f"_distill/wrap.py: {len(wrapped)} legacy posts wrapped, {len(live)} live: {', '.join(live) or 'none'}")


if __name__ == "__main__":
    sys.exit(main())
